runfile('C:/Users/Krish Nath/Stanford Course/dytstras shortest path algoritam.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')
runcell(0, 'C:/Users/Krish Nath/Stanford Course/untitled1.py')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
2 7 3
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled3.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled4.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled6.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled7.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled7.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled7.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled8.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled9.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Thu May 20 11:42:43 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled3.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled4.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled6.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Tue Jun 22 13:38:09 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Tue Jul  6 16:54:32 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled3.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled3.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Fri Jul  9 10:33:57 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/pograming assinment 2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/short path with obsticle.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled4.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/short path with obsticle.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled5.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled7.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled6.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled7.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled6.py', wdir='C:/Users/Krish Nath/Stanford Course')
runcell(0, 'C:/Users/Krish Nath/Stanford Course/untitled6.py')
runfile('C:/Users/Krish Nath/Stanford Course/untitled6.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled9.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled9.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled9.py', wdir='C:/Users/Krish Nath/Stanford Course')
5/3
sum([5,-3,3])
sum([5,-3,3])/3
runfile('C:/Users/Krish Nath/Stanford Course/untitled9.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled8.py', wdir='C:/Users/Krish Nath/Stanford Course')
debugfile('C:/Users/Krish Nath/Stanford Course/untitled8.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled8.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled10.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled11.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Wed Aug 18 10:30:06 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/untitled0.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled1.py', wdir='C:/Users/Krish Nath/Stanford Course')
runfile('C:/Users/Krish Nath/Stanford Course/untitled2.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Sun Nov  7 13:56:24 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/HappyBirthday.py', wdir='C:/Users/Krish Nath/Stanford Course')

## ---(Sun Nov  7 20:34:23 2021)---
runfile('C:/Users/Krish Nath/Stanford Course/HappyBirthday.py', wdir='C:/Users/Krish Nath/Stanford Course')